apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: v-170642bc4e016938
  namespace: bminfo
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ''
  volumeName: bminfo-v-170642bc4e016938
  resources:
    requests:
      storage: 1Gi
