apiVersion: v1
kind: PersistentVolume
metadata:
  name: bminfo-v-170642bc4e016938
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  claimRef:
    name: v-170642bc4e016938
    namespace: bminfo
  local:
    path: /opt/stacks/bminfo/pgadmin_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - spainip-k3s
