apiVersion: v1
kind: PersistentVolume
metadata:
  name: bminfo-v-f5b2c398ce5127fa
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  claimRef:
    name: v-f5b2c398ce5127fa
    namespace: bminfo
  local:
    path: /opt/stacks/bminfo/django_postgres_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - spainip-k3s
