apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: v-f5b2c398ce5127fa
  namespace: bminfo
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ''
  volumeName: bminfo-v-f5b2c398ce5127fa
  resources:
    requests:
      storage: 1Gi
