from django.urls import path

from . import core_views, auth_views, live_views, public_views, report_views


urlpatterns = [
    path("", core_views.dashboard, name="dashboard"),
    path("health/", public_views.health, name="health"),
    path("status/", public_views.status, name="status"),
    path("about/", public_views.about, name="about"),
    path("locales/<str:locale>/", public_views.locale_catalog, name="locale-catalog"),
    path("api/dashboard/", core_views.dashboard_api, name="dashboard-api"),
    path("api/stats/summary", core_views.dashboard_api, name="stats-summary"),
    path("api/qsos/", core_views.qsos_api, name="qsos-api"),
    path("api/talkgroups/", core_views.talkgroups_api, name="talkgroups-api"),
    path("api/continents/", core_views.continents_api, name="continents-api"),
    path("api/countries/", core_views.countries_api, name="countries-api"),
    path("api/live-qsos/", live_views.live_qsos_api, name="live-qsos-api"),
    path("public/stats", public_views.public_stats, name="public-stats"),
    path("public/lastheard", public_views.lastheard, name="public-lastheard"),
    path("public/lastheard/grouped", public_views.grouped_lastheard, name="public-talkgroups"),
    path("public/lastheard/callsigns", public_views.grouped_callsigns, name="public-callsigns"),
    path("public/continents", core_views.continents_api, name="public-continents"),
    path("public/countries", core_views.countries_api, name="public-countries"),
    path("public/talkgroups", core_views.talkgroups_api, name="public-talkgroups-list"),
    path("user/talkgroups", public_views.active_talkgroups, name="user-talkgroups"),
    path("user/live-qsos/", live_views.live_qsos, name="live-qsos"),
    path("reports/", report_views.reports, name="reports"),
    path("reports/data/", report_views.report_api, name="report-api"),
    path("reports/export.csv", report_views.report_csv, name="report-csv"),
    path("reports/export.xlsx", report_views.report_excel, name="report-excel"),
    path("reports/export.pdf", report_views.report_pdf, name="report-pdf"),
    path("login/", auth_views.login_view, name="login"),
    path("logout/", auth_views.logout_view, name="logout"),
    path("register/", auth_views.register, name="register"),
    path("verify/", auth_views.verify_email, name="verify-email"),
    path("forgot-password/", auth_views.forgot_password, name="forgot-password"),
    path("reset-password/", auth_views.reset_password, name="reset-password"),
    path("profile/", auth_views.profile, name="profile"),
    path("user/api/stats/", auth_views.api_stats, name="user-api-stats"),
    path("change-password/", auth_views.change_password, name="change-password"),
    path("change-email/", auth_views.start_email_change, name="change-email"),
    path("change-email/confirm/<str:stage>/", lambda request, stage: auth_views.confirm_email_change(request, stage), name="confirm-email-change"),
]
