# Generated by Django 6.1 on 2026-08-07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("auth", "0012_alter_user_first_name_max_length")]
    operations = [
        migrations.CreateModel(
            name="ServiceHeartbeat",
            fields=[
                ("service_name", models.CharField(max_length=80, primary_key=True, serialize=False)),
                ("last_seen_at", models.DateTimeField()),
            ],
            options={"db_table": "service_heartbeats"},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_superuser", models.BooleanField(default=False, help_text="Designates that this user has all permissions without explicitly assigning them.", verbose_name="superuser status")),
                ("callsign", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(db_column="password_hash", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("groups", models.ManyToManyField(blank=True, help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.", related_name="user_set", related_query_name="user", to="auth.group", verbose_name="groups")),
                ("user_permissions", models.ManyToManyField(blank=True, help_text="Specific permissions for this user.", related_name="user_set", related_query_name="user", to="auth.permission", verbose_name="user permissions")),
            ],
            options={"db_table": "users", "ordering": ["callsign"]},
        ),
        migrations.CreateModel(
            name="EmailChangeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("old_email", models.EmailField(max_length=254)),
                ("new_email", models.EmailField(max_length=254)),
                ("old_token_hash", models.CharField(max_length=128, unique=True)),
                ("new_token_hash", models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("old_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("new_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(db_column="user_id", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "email_change_requests"},
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(db_column="user_id", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "email_verification_tokens"},
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(db_column="user_id", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "password_reset_tokens"},
        ),
        migrations.CreateModel(
            name="RawEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payload_hash", models.CharField(max_length=64, unique=True)),
                ("session_id", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=80)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("stop_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "raw_events",
                "ordering": ["-received_at"],
                "indexes": [models.Index(fields=["-received_at"], name="raw_events_received_idx"), models.Index(fields=["session_id"], name="raw_events_session_idx")],
            },
        ),
        migrations.CreateModel(
            name="Talkgroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("talkgroup_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(default="XX", max_length=8)),
                ("continent", models.CharField(default="Other", max_length=80)),
                ("full_country_name", models.CharField(default="Other", max_length=120)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "talkgroups",
                "ordering": ["talkgroup_id"],
                "indexes": [models.Index(fields=["country"], name="talkgroups_country_idx"), models.Index(fields=["continent"], name="talkgroups_continent_idx")],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("user", models.ForeignKey(db_column="user_id", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "user_sessions"},
        ),
        migrations.CreateModel(
            name="QSO",
            fields=[
                ("session_id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("source_id", models.BigIntegerField(blank=True, null=True)),
                ("source_call", models.CharField(blank=True, max_length=32, null=True)),
                ("source_name", models.CharField(blank=True, max_length=255, null=True)),
                ("destination_call", models.CharField(blank=True, max_length=32, null=True)),
                ("destination_name", models.CharField(blank=True, max_length=255, null=True)),
                ("context_id", models.BigIntegerField(blank=True, null=True)),
                ("link_call", models.CharField(blank=True, max_length=64, null=True)),
                ("link_name", models.CharField(blank=True, max_length=255, null=True)),
                ("link_type_name", models.CharField(blank=True, max_length=120, null=True)),
                ("slot", models.SmallIntegerField(blank=True, null=True)),
                ("master", models.CharField(blank=True, max_length=255, null=True)),
                ("talker_alias", models.CharField(blank=True, max_length=255, null=True)),
                ("rssi", models.FloatField(blank=True, null=True)),
                ("ber", models.FloatField(blank=True, null=True)),
                ("start_at", models.DateTimeField()),
                ("stop_at", models.DateTimeField()),
                ("duration_ms", models.IntegerField()),
                ("is_native_session_id", models.BooleanField(default=True)),
                ("ingested_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("payload", models.JSONField(default=dict)),
                ("raw_event", models.ForeignKey(db_column="raw_event_id", on_delete=django.db.models.deletion.PROTECT, related_name="qsos", to="dashboard.rawevent")),
                ("talkgroup", models.ForeignKey(blank=True, db_column="destination_id", db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="qsos", to="dashboard.talkgroup", to_field="talkgroup_id")),
            ],
            options={
                "db_table": "qsos",
                "ordering": ["-start_at"],
                "indexes": [models.Index(fields=["-start_at"], name="qsos_start_idx"), models.Index(fields=["source_id", "-start_at"], name="qsos_source_start_idx"), models.Index(fields=["talkgroup", "-start_at"], name="qsos_dest_start_idx")],
            },
        ),
    ]
